name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
    types: [assigned, opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      
      - name: Installing platformio
        run: pip3 install -U platformio

      - name: Build current project using platformio 
        run: |
          pio lib install
          pio run
      
      - name: Prepare firmware files
        id: prepare
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          mkdir out
          cp ${{ github.workspace }}/.pio/build/core2_diff/firmware.bin out/firmware_diff.bin
          cp ${{ github.workspace }}/.pio/build/core2_mec/firmware.bin out/firmware_mec.bin

      - name: Upload firmware files
        uses: actions/upload-artifact@v2
        with:
          name: firmware_${{ steps.prepare.outputs.sha_short }}
          path: out/*